# Generated by Django 5.0.1 on 2024-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(default="nameless", max_length=100),
            preserve_default=False,
        ),
    ]
