# Generated by Django 4.2.7 on 2023-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitempost',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('services', 'Services'), ('vehicles', 'Vehicles'), ('fashion_beauty', 'Fashion & Beauty'), ('furniture', 'Furniture'), ('animals', 'Animals'), ('property_for_rent', 'Property for rent'), ('books', 'Books')], max_length=100, null=True),
        ),
    ]
