# Generated by Django 4.2.7 on 2023-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_alter_marketplaceitempost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplaceitempost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
