# Generated by Django 4.2.7 on 2024-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_marketplaceitempost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceitempost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="market_img/"),
        ),
    ]
