# Generated by Django 4.2.7 on 2024-01-10 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laikaprofileuser',
            name='laika_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lpu', to=settings.AUTH_USER_MODEL),
        ),
    ]
