# Generated by Django 4.2.7 on 2024-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laika', '0002_alter_laikaprofileuser_laika_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laikaprofileuser',
            name='image',
            field=models.ImageField(blank=True, default='laika_logo_400.png', null=True, upload_to='media/images/'),
        ),
    ]
