# Generated by Django 4.2.8 on 2023-12-16 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('recipient', models.IntegerField()),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_last', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_gender', models.BooleanField(null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('match_count', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=500)),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('play_date', models.DateTimeField()),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('level', models.CharField(choices=[('1', 'Novice'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert'), ('5', 'Master')], max_length=1)),
                ('language', models.CharField(choices=[('1', 'english'), ('2', 'duetsch'), ('3', 'spannish'), ('4', 'french'), ('5', 'persia')], max_length=1)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('club_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tennis_app.clubs')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('level', models.CharField(blank=True, choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Perfect')], max_length=1)),
                ('Post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tennis_app.posts')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
