# Generated by Django 4.2.7 on 2024-01-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
