# Generated by Django 4.2.6 on 2023-12-18 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='club_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='club_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='birth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'None')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
