# Generated by Django 4.2.7 on 2024-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0002_delete_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('recipient', models.IntegerField()),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
