# Generated by Django 4.2.6 on 2023-12-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0002_rename_comment_comments_remove_posts_club_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='match_count',
        ),
    ]
