# Generated by Django 4.2.8 on 2023-12-30 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0003_remove_posts_match_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='level',
            new_name='rank',
        ),
        migrations.AlterField(
            model_name='posts',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='play_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
