# Generated by Django 4.2.7 on 2024-01-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0003_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
