# Generated by Django 4.2.7 on 2024-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0004_alter_posts_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='language',
            field=models.CharField(choices=[('1', 'english'), ('2', 'deutsch'), ('3', 'spanish'), ('4', 'french'), ('5', 'persia')], max_length=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='level',
            field=models.CharField(choices=[('1', 'Novice'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert'), ('5', 'Master')], max_length=1),
        ),
    ]
