# Generated by Django 4.2.8 on 2024-01-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0004_rename_level_comments_rank_alter_posts_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Post_id',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='tennis_app/static/image/default.jpg', upload_to='tennis_app/static/image'),
        ),
    ]
