# Generated by Django 4.2.8 on 2024-01-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0005_rename_post_id_comments_post_alter_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='Post',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tennis_app.posts'),
        ),
    ]
