# Generated by Django 4.2.8 on 2024-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0006_remove_comments_post_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
