# Generated by Django 4.2.8 on 2024-01-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0007_alter_posts_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='language',
            field=models.CharField(choices=[('1', 'english'), ('2', 'deutsch'), ('3', 'spannish'), ('4', 'french'), ('5', 'persia')], max_length=1),
        ),
    ]
