# Generated by Django 4.2.8 on 2024-01-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0010_alter_posts_language_alter_posts_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='language',
            field=models.CharField(choices=[('A', 'Any'), ('1', 'english'), ('2', 'deutsch'), ('3', 'spanish'), ('4', 'french'), ('5', 'persia')], max_length=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='level',
            field=models.CharField(choices=[('A', 'Any'), ('1', 'Novice'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert'), ('5', 'Master')], max_length=1),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_gender',
            field=models.CharField(choices=[('A', 'Any'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
