# Generated by Django 4.2.7 on 2024-01-17 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0011_alter_posts_language_alter_posts_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
